[package]
name = "csvtools"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"
debug = true

[dependencies]
anyhow = { version = "1.0.91", features = ["backtrace"] }
clap = { version = "4.5.20", features = ["derive"] }
csv = "1.3.0"
lazy_static = "1.5.0"
memmap = "0.7.0"
